name: Fast_Team
description: Attendance everyday everywhere
title: Fast Team
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.2.4
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.2.0
  month_year_picker: ^0.3.0
  intl: ^0.19.0
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  timezone: ^0.9.1
  camera: ^0.10.5
  image: ^4.1.6
  pdf: ^3.6.0
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^24.2.3
  syncfusion_flutter_datepicker: ^24.2.3
  table_calendar: ^3.0.0
  image_picker: ^1.0.7
  sticky_headers: ^0.3.0+2
  month_picker_dialog: ^2.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  cached_network_image: ^3.2.0
  double_back_to_close_app: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  flutter_calendar_carousel: ^2.4.3
  stepper_list_view: ^0.0.1
  getwidget: ^2.0.4
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  path_provider: ^2.0.3
  file_picker: ^4.0.0
  permission_handler: ^11.3.1
  path: ^1.8.3
  flutter_downloader: ^1.11.7
  internet_connection_checker_plus: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  # month_year_picker: ^0.3.0
  flutter_custom_month_picker: ^0.1.3
  syncfusion_flutter_calendar: ^24.2.3
  accordion: ^2.6.0

dependency_overrides:
  intl: ^0.18.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/img/logoFP.png
    - assets/img/logo.png
    - assets/img/logo.jpg
    - assets/img/telat.jpg
    - assets/img/bgLogin.jpg
    - assets/img/bgWdigetCardAbsen.jpg
    - assets/img/centangSukses.png
    - assets/img/whatsapp.png
    - assets/img/logopanjang.png
    - assets/img/logo_besar.jpg
    - assets/img/noInternet.png
