name: fastteam_app
description: A new Flutter project.
version: 2.4.2+0
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.1.2
  cached_network_image: ^3.2.3
  flutter_svg:
  calendar_date_picker2: ^0.5.2
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.1.4
  country_pickers: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  image_picker_platform_interface: ^2.8.0
  pin_code_fields: ^7.4.0
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.0
  flutter_svg_provider: ^1.0.3
  colorful_safe_area: ^1.0.0
#  intl_phone_field: ^3.1.0
  intl: ^0.18.1
  pinput: ^2.2.31
#  image_picker_gallery_camera: ^0.2.2
  image_picker: ^0.8.9
  flutter_map: ^6.1.0
  timezone: ^0.9.1
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  camera: ^0.10.5
  url_launcher: ^6.2.4
  month_picker_dialog: ^2.0.1
  timeline_tile: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  time_picker_spinner_pop_up: ^1.5.0
  app_tracking_transparency: ^2.0.6

# When depending on this package from a real application you should use:
  #   image_picker: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.




dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true

  assets: 
    - assets/
    - assets/images/
    - assets/fastteam_image/
  fonts: 
    - family: Proxima Nova
      fonts: 
        - asset: assets/fonts/ProximaNovaBold.ttf
          weight: 700
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextSemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
